const data = [
    {
        id: 'a1b2c3d4e1',
        title: 'Python for absolute beginners',
        price: 4.99,
        category: 'Programing Language',
        instructor: 'Joseph Satlin',
        level: 'Beginner',
        enrolled: 240,
        language: 'English',
        img: '',

    },
    {
        id: 'a1b2c3d4e2',
        title: 'Data Science for  beginners',
        price: 9.99,
        category: 'Data Science',
        instructor: 'John Smith',
        level: 'Beginner',
        enrolled: 132,
        language: 'English',
        img: '',

    },
    {
        id: 'a1b2c3d4e3',
        title: 'Machine learning for university students',
        price: 4.99,
        category: 'Machine Learning',
        instructor: 'Andrew James',
        level: 'Beginner',
        enrolled: 355,
        language: 'English',
        img: '',

    },
    {
        id: 'a1b2c3d4e4',
        title: 'C programming for kids',
        price: 4.99,
        category: 'Programing Language',
        instructor: 'Sakil Hossain',
        level: 'Beginner',
        enrolled: 98,
        language: 'Bangla',
        img: '',

    },
    {
        id: 'a1b2c3d4e5',
        title: 'Intermediate python programming for data science',
        price: 14.99,
        category: 'Programing Language | Data Science',
        instructor: 'Istiak Ahmed',
        level: 'Intermediate',
        enrolled: 321,
        language: 'Bangla',
        img: '',

    },
    {
        id: 'a1b2c3d4e6',
        title: 'Full stack web development with python and react',
        price: 19.99,
        category: 'Programing Language | Web Development | Database',
        instructor: 'Sajjad Mahmud',
        level: 'Andvance',
        enrolled: 240,
        language: 'Bangla',
        img: '',

    },
    {
        id: 'a1b2c3d4e7',
        title: 'Database for absolute beginners',
        price: 4.99,
        category: 'Programing Language | Database',
        instructor: 'Rahul Bhatt',
        level: 'Beginner',
        enrolled: 267,
        language: 'Hindi',
        img: '',

    },
    {
        id: 'a1b2c3d4e8',
        title: 'Data visualization in python',
        price: 9.99,
        category: 'Programing Language | Data Visualization',
        instructor: 'Dinesh Majumdar',
        level: 'Beginner',
        enrolled: 150,
        language: 'Hindi',
        img: '',

    },
    {
        id: 'a1b2c3d4e9',
        title: 'Basic mathematics and statistics for data science',
        price: 4.99,
        category: 'Data Science | Mathematics | statistics',
        instructor: 'Sajol Kumar',
        level: 'Beginner',
        enrolled: 245,
        language: 'Bangla',
        img: '',

    },
    {
        id: 'a1b2c3d4e10',
        title: 'Python programming for teenager',
        price: 4.99,
        category: 'Programing Language',
        instructor: 'James Deen',
        level: 'Beginner',
        enrolled: 251,
        language: 'English',
        img: '',

    },
]